This rule raises an issue when a generic exception (such as ``++std::exception++``, ``++std::logic_error++`` or ``++std::runtime_error++``) is thrown.

== Why is this an issue?

Throwing generic exceptions such as ``++std::exception++``, ``++std::logic_error++`` and ``++std::runtime_error++`` will have a negative impact on any code trying to catch these exceptions.

When working with a generic type of exception, the only way to distinguish between multiple exceptions is to check their message, which is error-prone and difficult to maintain.

From a consumer perspective, it is generally a best practice to only catch exceptions you intend to handle. Other exceptions should ideally not be caught and let to propagate up the stack trace so that they can be dealt with appropriately. When a generic exception is thrown, it forces consumers to catch exceptions they do not intend to handle, which they then have to re-throw.

At best, this makes the code hard to understand and maintain. At worst, legitimate exceptions may be unintentionally silenced and errors may be hidden. For instance, if an exception such as `std::bad_alloc` is caught and not re-thrown, it will prevent the program from terminating gracefully.

When throwing an exception, it is therefore recommended to throw the most specific exception possible so that it can be handled intentionally by consumers.

== How to fix it

To fix this issue, make sure to throw specific exceptions that are relevant to the context in which they arise. It is recommended to either:

* Throw a subtype of `++std::exception++`` when one matches. For instance ``++std::invalid_argument++`` could be raised when an unexpected argument is provided to a function.
* Define a custom exception type that derives from `++std::exception++`` or one of its subclasses.

=== Code examples

==== Noncompliant code example

[source,cpp,diff-id=1,diff-type=noncompliant]
----
#include <stdexcept>

void checkValue(int value) {
    if (value < 0) {
        throw std::logic_error("Value cannot be negative"); // Noncompliant: this will be difficult for consumers to handle
    }
}
----

==== Compliant solution

[source,cpp,diff-id=1,diff-type=compliant]
----
#include <stdexcept>

void checkValue(int value) {
    if (value < 0) {
        throw std::invalid_argument("Value cannot be negative"); // Compliant
    }
}
----

== Resources

* https://cwe.mitre.org/data/definitions/397[MITRE, CWE-397] - Declaration of Throws for Generic Exception
* https://wiki.sei.cmu.edu/confluence/x/_DdGBQ[CERT, ERR07-J.] - Do not throw RuntimeException, Exception, or Throwable
* https://github.com/isocpp/CppCoreGuidelines/blob/036324/CppCoreGuidelines.md#Re-exception-types[{cpp} Core Guidelines E.14] - Use purpose-designed user-defined types as exceptions (not built-in types)

ifdef::env-github,rspecator-view[]

'''
== Implementation Specification
(visible only on this page)

include::../message.adoc[]

'''

endif::env-github,rspecator-view[]
